steps:
  - label: ":docker: Image Deployments"
    command: ".buildkite/steps/deployimages.sh | buildkite-agent pipeline upload"
    concurrency: 1
    concurrency_group: "deployments"

  - wait

  - label: ":docker: Deploy Manifests"
    command: "authelia-scripts docker push-manifest"
    concurrency: 1
    concurrency_group: "deployments"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

  - label: ":github: Deploy Artifacts"
    command: ".buildkite/steps/ghartifacts.sh"
    agents:
      upload: "fast"
    key: "artifacts"
    if: build.tag != null

  - label: ":linux: Deploy AUR"
    command: ".buildkite/steps/aurpackages.sh | buildkite-agent pipeline upload"
    if: build.tag != null || build.branch == "master"

  - label: ":docs: Deploy documentation"
    command: "authelia-scripts documentation deploy"
    if: build.tag != null || build.branch == "master"